version: '3.5'

services:
  angular-app:
    build: .
    container_name: angular-app
    ports:
      - '4200:4200'
    volumes:
      - type: bind
        source: ./aquapp-front
        target: /aquapp-front
    environment:
      - STYLE=css
    env_file:
      - .env